/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.kittech0.jawlite;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() throws ClassNotFoundException {
        Class.forName("io.github.kittech0.jawlite.Library");
    }
}
