/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.kittech0.jawlite;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

public class Library {
    static {
        try {
            Connection connection = DriverManager.getConnection("jdbc:sqlite:jawlite.db");
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }
}
